#server:
#  port: 8090
#spring:
#  application:
#    name: gateway-zuul
#management:
#  security:
#    enabled: false
#zuul:
#  routes:
#    user-service: /user/**
#  ignored-services:
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000


