server:
  port: 8092
spring:
  application:
    name: config-server
    #user location profiles
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/share/
        git:
          uri: https://github.com/liuguangxin1hao/server.git
          username:
          password:
eureka:
  client:
    health-check:
      enabled: true
    service-url:
      defaultZone: http://localhost:8071/eureka/
    instance:
      filter-only-up-instances: true
management:
  security:
    enabled: false
