#spring:
#  application:
#    name: user
#server:
#  port: 8080
#eureka:
#  client:
#    health-check:
#      enabled: true
#    serviceUrl:
#      defaultZone: http://11.11.48.6:8071/eureka/
#  instance:
#    filter-only-up-instances: true
#    prefer-ip-address: true
#    hostname: ${spring.cloud.client.ipAddress}
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#management:
#  security:
#    enabled: false