spring:
  profiles:
    active: peer1
server:
  port: 8071
eureka:
  server:
   enable-self-preservation: false
   eviction-interval-timer-in-ms: 3000
  instance:
    hostname: peer1
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 3
  client:
    register-with-eureka: true
    fetch-registry: true
    health-check:
      enabled: true
    service-url:
      defaultZone: http://peer2:8072/eureka/,http://peer3:8073/eureka/
#security:
#  basic:
#    enabled: true
#  user:
#    name: root
#    password: 123456