spring:
  profiles:
    active: peer2
server:
  port: 8072
eureka:
  server:
   enable-self-preservation: false
   eviction-interval-timer-in-ms: 3000
  instance:
    hostname: peer2
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 3
  client:
    register-with-eureka: true
    fetch-registry: true
    health-check:
      enabled: true
    service-url:
      defaultZone: http://peer1:8071/eureka/,http://peer3:8073/eureka/
