spring:
  profiles:
    active: peer2
  application:
    name: eureka
---
spring:
  profiles:
    active: peer1
server:
  port: 8071
eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    health-check:
      enabled: true
    service-url:
      defaultZone: http://peer2:8072/eureka/,http://peer3:8073/eureka/
---
spring:
  profiles:
    active: peer2
server:
  port: 8072
eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    health-check:
      enabled: true
    service-url:
      defaultZone: http://peer1:8071/eureka/,http://peer3:8073/eureka/
---
spring:
  profiles:
    active: peer3
server:
  port: 8073
eureka:
  instance:
    hostname: peer3
  client:
    register-with-eureka: true
    fetch-registry: true
    health-check:
      enabled: true
    service-url:
      defaultZone: http://peer1:8071/eureka/,http://peer2:8072/eureka/
