spring:
  application:
    name: provider-service
  zipkin:
    base-url: http://localhost:8099
  sleuth:
    sampler:
      percentage: 1.0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/liu?useSSL=false
    username: root
    password: lgx11111
    driver-class-name: com.mysql.jdbc.Driver
from: 44www
