server:
  port: 7090
spring:
  application:
    name: config-server
    #user location profiles
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/share/
#        git:
#          uri: https://github.com/liuguangxin1hao/server.git
#      label: master
#          username:
#          password:
        git:
          uri: http://11.10.135.30/SpringCloudDev/spring-cloud-config.git
          username: root
          password: abcd1234

eureka:
  client:
    health-check:
      enabled: true
    service-url:
      defaultZone: http://localhost:8071/eureka/
      #defaultZone: http://11.11.48.6:8071/eureka/
  instance:
    filter-only-up-instances: true
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
management:
  security:
    enabled: false
