spring:
  application:
    name: eureka
  profiles:
    active: peer1
server:
  port: 8073
eureka:
  instance:
    hostname: peer3
  client:
    register-with-eureka: true
    fetch-registry: true
    health-check:
      enabled: true
    service-url:
      defaultZone: http://peer1:8071/eureka/,http://peer2:8072/eureka/
